name: latvija_discount
description: A discount/flyer aggregator app for Latvian supermarkets.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pdfx: ^2.6.0
  page_flip: ^0.2.5+1
  path_provider: ^2.1.0
  http: ^1.6.0
  cupertino_icons: ^1.0.6
  animated_background: ^2.0.0
  carousel_slider: ^5.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/symbols/rimiSymbol.png
    - assets/symbols/maximaSymbol.png
    - assets/symbols/lidlSymbol.png